server:
  port: 8090
spring:
  application:
    name: auth-web
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery: 
        healthCheckPath: /health
        enabled: true
        instanceId: ${spring.application.name}:${random.value}